#!/usr/bin/env python3
"""
Direct Browser Download Script for Massive Setfile
Bypasses Rust/Tauri entirely - generates and triggers browser download
"""

import json
import os
from datetime import datetime
from http.server import HTTPServer, SimpleHTTPRequestHandler
import webbrowser
import threading
import time

# Configuration
PORT = 8765
OUTPUT_DIR = r"D:\trading_ecosystem_11\trading_ecosystem_9.0\main_ecosystem_trading\APPS\dashboard\logic-canvas-main\Vault_Presets"

def generate_setfile_content():
    """Generate the massive setfile content"""
    
    GROUPS = 15
    ENGINES = ['A', 'B', 'C']
    LOGICS = ['Power', 'Repower', 'Scalp', 'Stopper', 'STO', 'SCA', 'RPO']
    DIRECTIONS = ['Buy', 'Sell']
    
    LOGIC_SUFFIX = {
        'Power': 'P', 'Repower': 'R', 'Scalp': 'S',
        'Stopper': 'T', 'STO': 'O', 'SCA': 'C', 'RPO': 'X'
    }
    
    lines = []
    
    # Header
    lines.append("; DAAVILEFX MASSIVE CONFIGURATION SETFILE")
    lines.append(f"; Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    lines.append("; Version: 19.0 MASSIVE")
    lines.append("; Platform: MT4")
    lines.append(f"; Structure: {GROUPS} groups × {len(ENGINES)} engines × {len(LOGICS)} logics × {len(DIRECTIONS)} directions")
    lines.append(f"; Total Logic-Directions: {GROUPS * len(ENGINES) * len(LOGICS) * len(DIRECTIONS)}")
    lines.append(";")
    lines.append("; Generated by Dashboard - Direct Browser Export")
    lines.append("; ============================================\n")
    
    # Global Settings
    lines.append("; GLOBAL SETTINGS")
    lines.append("; ============================================")
    lines.append("gInput_MagicNumber=777")
    lines.append("gInput_MagicNumberBuy=888")
    lines.append("gInput_MagicNumberSell=999")
    lines.append("gInput_MaxOrders=150")
    lines.append("gInput_AutoCompounding=0")
    lines.append("")
    
    # Generate all logic configurations
    for group in range(1, GROUPS + 1):
        lines.append(f"; Group {group}")
        
        for engine in ENGINES:
            for logic in LOGICS:
                suffix = LOGIC_SUFFIX[logic]
                
                for direction in DIRECTIONS:
                    prefix = f"gInput_{group}_{engine}{suffix}_{direction}"
                    
                    # Lot sizing - progressive by group
                    if group <= 5:
                        initial_lot = 0.02
                        max_lot = 0.20
                    elif group <= 10:
                        initial_lot = 0.03
                        max_lot = 0.30
                    else:
                        initial_lot = 0.05
                        max_lot = 0.50
                    
                    grid = 100 + (group * 20)
                    multiplier = 1.20 + (group * 0.02)
                    trail = 5.0 + (group * 0.5)
                    tp = 50.0 + (group * 10)
                    sl = 30.0 + (group * 5)
                    
                    # Base settings
                    lines.append(f"{prefix}_Enabled=1")
                    lines.append(f"{prefix}_InitialLot={initial_lot}")
                    lines.append(f"{prefix}_LastLot={max_lot}")
                    lines.append(f"{prefix}_Multiplier={multiplier:.2f}")
                    lines.append(f"{prefix}_Grid={grid}")
                    lines.append(f"{prefix}_TrailMethod=0")
                    lines.append(f"{prefix}_TrailValue={trail:.1f}")
                    lines.append(f"{prefix}_TrailStart={group * 2.0}")
                    lines.append(f"{prefix}_TrailStep={trail:.1f}")
                    lines.append(f"{prefix}_UseTP=1")
                    lines.append(f"{prefix}_TakeProfit={tp:.1f}")
                    lines.append(f"{prefix}_TPMode=0")
                    lines.append(f"{prefix}_UseSL=1")
                    lines.append(f"{prefix}_StopLoss={sl:.1f}")
                    lines.append(f"{prefix}_SLMode=0")
                    lines.append(f"{prefix}_BreakEvenMode=0")
                    lines.append(f"{prefix}_BreakEvenActivation={20.0 + (group * 2.0)}")
                    lines.append(f"{prefix}_BreakEvenLock={10.0 + group}")
                    lines.append(f"{prefix}_BreakEvenTrail=0")
                    lines.append(f"{prefix}_ProfitTrailEnabled=0")
                    lines.append(f"{prefix}_TriggerType=0")
                    lines.append(f"{prefix}_TriggerBars=0")
                    lines.append(f"{prefix}_TriggerMinutes=0")
                    lines.append(f"{prefix}_TriggerPips=0.0")
                    lines.append(f"{prefix}_ReverseReference=0")
                    lines.append(f"{prefix}_HedgeReference=0")
                    lines.append(f"{prefix}_OrderCountRefLogic=0")
                    lines.append(f"{prefix}_ReverseScale=1.0")
                    lines.append(f"{prefix}_HedgeScale=1.0")
                    lines.append(f"{prefix}_ReverseEnabled=0")
                    lines.append(f"{prefix}_HedgeEnabled=0")
                    lines.append(f"{prefix}_CloseTargets=0")
                    lines.append(f"{prefix}_OrderCountRef=0")
                    lines.append(f"{prefix}_StartLevel=0" if logic == 'Power' else f"{prefix}_StartLevel={group}")
                    lines.append(f"{prefix}_ResetLotOnRestart=1")
                    lines.append(f"{prefix}_RestartPolicy=0")
                    
                    # Partial closes (4 levels)
                    for p in range(1, 5):
                        lines.append(f"{prefix}_PartialEnabled{p}=0")
                        lines.append(f"{prefix}_PartialCycle{p}={p + 1}")
                        lines.append(f"{prefix}_PartialMode{p}=1")
                        lines.append(f"{prefix}_PartialBalance{p}=1")
                        lines.append(f"{prefix}_PartialTrailMode{p}=0")
                        lines.append(f"{prefix}_PartialTrigger{p}=0")
                        lines.append(f"{prefix}_PartialProfitThreshold{p}=0.0")
                        lines.append(f"{prefix}_PartialHours{p}=0")
                    
                    lines.append("")  # Blank line
    
    # Footer
    lines.append("; ============================================")
    lines.append("; END OF CONFIGURATION")
    lines.append("; ============================================")
    
    return '\n'.join(lines)

class CustomHandler(SimpleHTTPRequestHandler):
    def do_POST(self):
        """Handle POST with setfile content and trigger download"""
        content_length = int(self.headers['Content-Length'])
        post_data = self.rfile.read(content_length)
        
        # Save file
        output_file = os.path.join(OUTPUT_DIR, "DOWNLOAD_MASSIVE.set")
        with open(output_file, 'wb') as f:
            f.write(post_data)
        
        # Count lines
        lines = post_data.decode('utf-8').split('\n')
        
        self.send_response(200)
        self.send_header('Content-Type', 'application/json')
        self.end_headers()
        self.wfile.write(json.dumps({
            'success': True,
            'file': output_file,
            'lines': len(lines)
        }).encode())
    
    def do_GET(self):
        """Serve a simple HTML page with download button"""
        if self.path == '/' or self.path == '/download':
            html = f"""
            <!DOCTYPE html>
            <html>
            <head>
                <title>Download Massive Setfile</title>
                <style>
                    body {{ font-family: Arial, sans-serif; padding: 50px; text-align: center; }}
                    button {{ 
                        padding: 20px 40px; font-size: 20px; 
                        background: #22c55e; color: white; border: none; 
                        border-radius: 8px; cursor: pointer; margin: 20px;
                    }}
                    button:hover {{ background: #16a34a; }}
                    .info {{ color: #666; margin: 20px; }}
                </style>
            </head>
            <body>
                <h1>📥 Download MASSIVE Setfile</h1>
                <p class="info">This will generate and download a 55,000+ input setfile directly</p>
                <button onclick="generateAndDownload()">Generate & Download</button>
                <div id="status"></div>
                
                <script>
                    async function generateAndDownload() {{
                        document.getElementById('status').innerHTML = 'Generating...';
                        
                        const response = await fetch('/generate', {{ method: 'POST' }});
                        const data = await response.json();
                        
                        if (data.success) {{
                            // Trigger download
                            const link = document.createElement('a');
                            link.href = 'file://{output_file.replace(chr(92), '/')}';
                            link.download = 'DAAVILEFX_MASSIVE_DOWNLOAD.set';
                            document.getElementById('status').innerHTML = 
                                `✅ Generated! Lines: ${{data.lines}}<br>Saved to: ${{data.file}}`;
                        }} else {{
                            document.getElementById('status').innerHTML = '❌ Error: ' + data.error;
                        }}
                    }}
                </script>
            </body>
            </html>
            """
            self.send_response(200)
            self.send_header('Content-type', 'text/html')
            self.end_headers()
            self.wfile.write(html.encode())
        elif self.path == '/generate':
            # Generate setfile
            content = generate_setfile_content()
            
            # Save to file
            output_file = os.path.join(OUTPUT_DIR, "DOWNLOAD_MASSIVE.set")
            with open(output_file, 'w', encoding='utf-8') as f:
                f.write(content)
            
            lines = content.split('\n')
            
            self.send_response(200)
            self.send_header('Content-Type', 'application/json')
            self.end_headers()
            self.wfile.write(json.dumps({
                'success': True,
                'file': output_file,
                'lines': len(lines),
                'size_mb': os.path.getsize(output_file) / (1024*1024)
            }).encode())
        else:
            super().do_GET()

def main():
    """Start server and open browser"""
    server = HTTPServer(('localhost', PORT), CustomHandler)
    print(f"""
╔══════════════════════════════════════════════════════════════╗
║  MASSIVE SETFILE DIRECT DOWNLOAD SERVER                    ║
╠══════════════════════════════════════════════════════════════╣
║  Status: Starting...                                     ║
║  Port: {PORT}                                              ║
║  Output: {OUTPUT_DIR[:50]}...                            ║
╠══════════════════════════════════════════════════════════════╣
║  Opening browser...                                       ║
║  Click "Generate & Download" button                       ║
╚══════════════════════════════════════════════════════════════╝
    """)
    
    # Open browser
    threading.Timer(1.0, lambda: webbrowser.open(f'http://localhost:{PORT}/download')).start()
    
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("\nServer stopped.")
        server.shutdown()

if __name__ == "__main__":
    main()
