import { MTConfig } from "@/types/mt-config";

export const LOGICS = ["Power", "Repower", "Scalp", "Stopper", "STO", "SCA", "RPO"] as const;
export const ENGINES = ["A", "B", "C"] as const;

export type LogicType = typeof LOGICS[number];
export type EngineType = typeof ENGINES[number];

const LOGIC_CODES: Record<LogicType, string> = {
  "Power": "P",
  "Repower": "R",
  "Scalp": "S",
  "Stopper": "ST",
  "STO": "STO",
  "SCA": "SCA",
  "RPO": "RPO",
};

const PARAM_NAMES = [
  "Start",
  "AllowBuy",
  "AllowSell",
  "Initial_loT",
  "Mult",
  "Grid",
  "MaxPowerOrders",
  "LastLotPower",
  "Trail",
  "TrailValue",
  "Trail_Start",
  "TrailStep",
  "TrailStepMethod",
  "TrailStepCycle",
  "TrailStepBalance",
  "TrailStepMode",
  "TrailStep2",
  "TrailStepMethod2",
  "TrailStepCycle2",
  "TrailStepBalance2",
  "TrailStepMode2",
  "TrailStep3",
  "TrailStepMethod3",
  "TrailStepCycle3",
  "TrailStepBalance3",
  "TrailStepMode3",
  "TrailStep4",
  "TrailStepMethod4",
  "TrailStepCycle4",
  "TrailStepBalance4",
  "TrailStepMode4",
  "TrailStep5",
  "TrailStepMethod5",
  "TrailStepCycle5",
  "TrailStepBalance5",
  "TrailStepMode5",
  "TrailStep6",
  "TrailStepMethod6",
  "TrailStepCycle6",
  "TrailStepBalance6",
  "TrailStepMode6",
  "TrailStep7",
  "TrailStepMethod7",
  "TrailStepCycle7",
  "TrailStepBalance7",
  "TrailStepMode7",
  "ClosePartial",
  "ClosePartialCycle",
  "ClosePartialMode",
  "ClosePartialBalance",
  "ClosePartial2",
  "ClosePartialCycle2",
  "ClosePartialMode2",
  "ClosePartialBalance2",
  "ClosePartial3",
  "ClosePartialCycle3",
  "ClosePartialMode3",
  "ClosePartialBalance3",
  "ClosePartial4",
  "ClosePartialCycle4",
  "ClosePartialMode4",
  "ClosePartialBalance4",
  "CloseTargets",
  "OrderCountReference",
  "ResetLotOnRestart",
  "RestartPolicy",
  "UseTP",
  "TPMode",
  "TPValue",
  "UseSL",
  "SLMode",
  "SLValue",
  "BreakEvenMode",
  "BreakEvenActivation",
  "BreakEvenLock",
  "BreakEvenTrail",
  "GridBehavior",
  "ReverseEnabled",
  "ReverseReference",
  "ReverseScale",
  "HedgeEnabled",
  "HedgeReference",
  "HedgeScale",
  "TriggerType",
  "TriggerBars",
  "TriggerMinutes",
  "TriggerPips",
  "StartLevel",
];

interface V3LegacyValues {
  grid: number;
  initialLot: number;
  lastLot: number;
  multiplier: number;
  startLevel: number;
  trailMethod: number;
}

function getV3LegacyValues(group: number, logic: LogicType, engine: EngineType): V3LegacyValues {
  if (group === 1 && logic === "Power" && engine === "A") {
    return {
      grid: 600,
      initialLot: 0.02,
      lastLot: 0.63,
      multiplier: 1.2,
      startLevel: 0,
      trailMethod: 0,
    };
  }
  return {
    grid: logic === "Power" ? 600 : 300,
    initialLot: 0.02,
    lastLot: 0.12,
    multiplier: group === 1 ? 1.2 : 1.4,
    startLevel: 4,
    trailMethod: group === 1 ? 0 : 1,
  };
}

function buildParamName(param: string, logic: LogicType, group: number, engine: EngineType, direction: "Buy" | "Sell"): string {
  const suffix = direction === "Buy" ? "" : "_Sell";
  const enginePrefix = engine === "A" ? "" : engine;
  const logicCode = LOGIC_CODES[logic];
  return `gInput_${param}_${enginePrefix}${logicCode}${group}${suffix}`;
}

export function generateCompleteSetfile(config: MTConfig): string {
  const lines: string[] = [];

  lines.push("; DAAVILEFX V4 - COMPLETE V3 LEGACY SETFILE");
  lines.push("; Generated by Dashboard");
  lines.push("; Groups: 15, Engines: 3, Logics: 7, Directions: 2");
  lines.push("; Total: 15x3x7x2 = 630 logic-directions");
  lines.push("");

  for (let group = 1; group <= 15; group++) {
    lines.push(`; ============================================`);
    lines.push(`; GROUP ${group}`);
    lines.push(`; ============================================`);

    for (const engine of ENGINES) {
      lines.push(`; Engine ${engine}`);

      for (const logic of LOGICS) {
        for (const direction of ["Buy", "Sell"] as const) {
          lines.push(`; Group ${group} - Engine ${engine} - ${logic} - ${direction}`);

          const v3Values = getV3LegacyValues(group, logic, engine);

          for (const param of PARAM_NAMES) {
            const paramName = buildParamName(param, logic, group, engine, direction);
            let value: string | number = "";

            switch (param) {
              case "Start":
                value = 1;
                break;
              case "AllowBuy":
              case "AllowSell":
                value = 1;
                break;
              case "Initial_loT":
                value = v3Values.initialLot.toFixed(2);
                break;
              case "Mult":
                value = v3Values.multiplier;
                break;
              case "Grid":
                value = v3Values.grid;
                break;
              case "MaxPowerOrders":
                value = 10;
                break;
              case "LastLotPower":
                value = v3Values.lastLot.toFixed(2);
                break;
              case "Trail":
                value = v3Values.trailMethod;
                break;
              case "TrailValue":
                value = 300;
                break;
              case "Trail_Start":
                value = 300;
                break;
              case "TrailStep":
                value = 150;
                break;
              case "TrailStepMethod":
              case "TrailStepMethod2":
              case "TrailStepMethod3":
              case "TrailStepMethod4":
              case "TrailStepMethod5":
              case "TrailStepMethod6":
              case "TrailStepMethod7":
                value = 0;
                break;
              case "TrailStepCycle":
                value = 1;
                break;
              case "TrailStepCycle2":
                value = 2;
                break;
              case "TrailStepCycle3":
                value = 3;
                break;
              case "TrailStepCycle4":
                value = 4;
                break;
              case "TrailStepCycle5":
                value = 5;
                break;
              case "TrailStepCycle6":
                value = 6;
                break;
              case "TrailStepCycle7":
                value = 7;
                break;
              case "TrailStepBalance":
              case "TrailStepBalance2":
              case "TrailStepBalance3":
              case "TrailStepBalance4":
              case "TrailStepBalance5":
              case "TrailStepBalance6":
              case "TrailStepBalance7":
                value = 0;
                break;
              case "TrailStepMode":
              case "TrailStepMode2":
              case "TrailStepMode3":
              case "TrailStepMode4":
              case "TrailStepMode5":
              case "TrailStepMode6":
              case "TrailStepMode7":
              case "TrailStep2":
              case "TrailStep3":
              case "TrailStep4":
              case "TrailStep5":
              case "TrailStep6":
              case "TrailStep7":
                value = 0;
                break;
              case "ClosePartial":
              case "ClosePartial2":
              case "ClosePartial3":
              case "ClosePartial4":
                value = 0;
                break;
              case "ClosePartialCycle":
              case "ClosePartialCycle2":
              case "ClosePartialCycle3":
              case "ClosePartialCycle4":
                value = 3;
                break;
              case "ClosePartialMode":
                value = 1;
                break;
              case "ClosePartialMode2":
              case "ClosePartialMode3":
              case "ClosePartialMode4":
                value = 0;
                break;
              case "ClosePartialBalance":
              case "ClosePartialBalance2":
              case "ClosePartialBalance3":
              case "ClosePartialBalance4":
                value = 0;
                break;
              case "CloseTargets":
                value = "";
                break;
              case "OrderCountReference":
                value = 10;
                break;
              case "ResetLotOnRestart":
                value = 1;
                break;
              case "RestartPolicy":
                value = 0;
                break;
              case "UseTP":
              case "UseSL":
                value = 0;
                break;
              case "TPMode":
              case "SLMode":
                value = 0;
                break;
              case "TPValue":
              case "SLValue":
                value = 0;
                break;
              case "BreakEvenMode":
              case "BreakEvenActivation":
              case "BreakEvenLock":
              case "BreakEvenTrail":
                value = 0;
                break;
              case "GridBehavior":
                value = 0;
                break;
              case "ReverseEnabled":
              case "ReverseReference":
              case "ReverseScale":
              case "HedgeEnabled":
              case "HedgeReference":
              case "HedgeScale":
                value = 0;
                break;
              case "TriggerType":
              case "TriggerBars":
              case "TriggerMinutes":
              case "TriggerPips":
                value = 0;
                break;
              case "StartLevel":
                value = v3Values.startLevel;
                break;
              default:
                value = 0;
            }

            lines.push(`${paramName}=${value}`);
          }
        }
      }
    }
  }

  lines.push("");
  lines.push("; End of xauusd_hardcoded_1.set");

  return lines.join("\n");
}

export function getTotalLines(): number {
  let lines = 5;
  for (let group = 1; group <= 15; group++) {
    lines += 3;
    for (const engine of ENGINES) {
      lines += 1;
      for (const logic of LOGICS) {
        for (const direction of ["Buy", "Sell"] as const) {
          lines += 1;
          lines += PARAM_NAMES.length;
        }
      }
    }
  }
  lines += 2;
  return lines;
}

export function getExpectedLineCount(): number {
  return getTotalLines();
}
